# coding: utf-8

"""
    perf::act Documentation API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: documentation@perf-act.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import openapi_client
from openapi_client.models.error_item import ErrorItem  # noqa: E501
from openapi_client.rest import ApiException

class TestErrorItem(unittest.TestCase):
    """ErrorItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ErrorItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = openapi_client.models.error_item.ErrorItem()  # noqa: E501
        if include_optional :
            return ErrorItem(
                field = '0', 
                code = '0', 
                message = '0'
            )
        else :
            return ErrorItem(
        )

    def testErrorItem(self):
        """Test ErrorItem"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
