# coding: utf-8

"""
    perf::act Documentation API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: documentation@perf-act.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.document_api import DocumentApi  # noqa: E501
from openapi_client.rest import ApiException


class TestDocumentApi(unittest.TestCase):
    """DocumentApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.document_api.DocumentApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_new_document(self):
        """Test case for add_new_document

        adds a new document  # noqa: E501
        """
        pass

    def test_add_new_document_for_template(self):
        """Test case for add_new_document_for_template

        adds a new document by template  # noqa: E501
        """
        pass

    def test_get_document(self):
        """Test case for get_document

        get latest updated documents  # noqa: E501
        """
        pass

    def test_get_latest_documents(self):
        """Test case for get_latest_documents

        get latest updated documents  # noqa: E501
        """
        pass

    def test_search_documents(self):
        """Test case for search_documents

        search for documents  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
